// Automatically generated by build-language-data.ts
import en from "content/messages-compiled/en.json";

export const localeToMessages = {
    "en": en,
} as const;

export const localeToLanguageName = {
    "en": "English",
} as const;
