// Automatically generated by build-language-data.ts
import en_XA from "content/messages-compiled/en-XA.json";
import en from "content/messages-compiled/en.json";

export const localeToMessages = {
    "en-XA": en_XA,
    "en": en,
} as const;

export const localeToLanguageName = {
    "en-XA": "[Ḗƞɠŀīşħ]",
    "en": "English",
} as const;
